apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-lb
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    name: http-grafana
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
