apiVersion: v1
kind: Service
metadata:
  labels:
    app: elk
  name: elk-lb
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    name: http-kibana
    protocol: TCP
    targetPort: 5601
  - port: 9200
    name: http-elastic
    protocol: TCP
    targetPort: 9200
  selector:
    app: elk
